services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
  frontend:
    build: ./chatbot-frontend
    ports:
      - "3000:3000"
    env_file:
      - ./chatbot-frontend/.env
    depends_on:
      - backend